name: Pre-Deployment Database Check

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main]

jobs:
  database-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check TypeScript compilation
      run: npm run typecheck
    
    - name: Check Prisma migrations
      run: npx prisma migrate status
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    - name: Run deployment readiness check
      run: npm run check:deploy
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
    - name: Comment on PR
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Pre-deployment checks failed! Please run `npm run check:deploy` locally and fix any issues before merging.'
          })